### ISSUE TITLE
chore: declared variable is not used

### ISSUE THREAD

**Issue by namkyu1999** [litmuschaos/litmus#4386]
This result of append is never used. @Saranya-jena added this variable. Can you take a look at this code?

https://github.com/litmuschaos/litmus/blob/399af62ca877c265160ea9edc6a2b8ee1b7f5f9d/chaoscenter/graphql/server/pkg/chaos_experiment/ops/service.go#L724-L727

**Comment by nanu1605** [comment]
Hi @namkyu1999, The result of the `append` operation is never used, might be a slight possibility that the code is incomplete

**Comment by kanhaiya04** [comment]
I want to work on this.

I think we have to return the `probes` in the `UpdateRuntimeCronWorkflowConfiguration` func as well.
@Saranya-jena, need your view before proceeding.

**Comment by Saranya-jena** [comment]
Going on the first come basis, @prashantrewar are you still interested in working on this issue?

**Comment by prashantrewar** [comment]
Hey @Saranya-jena and @kanhaiya04, I think the issue is resolved in this [PR](https://github.com/litmuschaos/litmus/pull/4366).

**Comment by namkyu1999** [comment]
@prashantrewar this issue is not resolved, anyone who wants to work on this issue, please raise a pr 😄

**Comment by rootxrishabh** [comment]
@namkyu1999 @Saranya-jena If possible, I can take this up!

**Comment by namkyu1999** [comment]
Hey @prashantrewar , let me know if you are interested in working on this issue, if not I will assign this issue to @rootxrishabh

**Comment by namkyu1999** [comment]
can you share the updates @rootxrishabh ?

**Comment by rootxrishabh** [comment]
@namkyu1999 I'm unable to take on this task at the moment. My apologies. @MichaelMorrisEst has already made a PR addressing the issue. Right?

**Comment by namkyu1999** [comment]
np @rootxrishabh 😄
